### ISSUE TITLE
Adicionar suporte para chamadas PATCH

### ISSUE THREAD

**Issue by danilocolombi** [lzocateli/Nuuvify.CommonPack#54]
Adicionar suporte ao verbo HTTP PATCH na biblioteca Nuuvify.CommonPack.StandardHttpClient

Há um método Patch hoje no arquivo [StandardHttpClientVerb](https://github.com/lzocateli/Nuuvify.CommonPack/blob/main/src/Nuuvify.CommonPack.StandardHttpClient/Implementation/StandardHttpClientVerbs.cs), porém ele faz uma requisição PUT.

![image](https://user-images.githubusercontent.com/41966783/234654957-e5a43fdd-cbeb-4eae-a1b2-446211f89567.png)

**Comment by lzocateli** [comment]
Versão preview gerada #56 e #57

**Comment by danilocolombi** [comment]
Resolvido
